export const AUTH_CONSTANTS = {
  MAX_FAILED_ATTEMPTS: 5,
  LOCK_DURATION_MINUTES: 15,
  PASSWORD_RESET_TOKEN_TTL_HOURS: 1,
  EMAIL_VERIFICATION_TOKEN_TTL_HOURS: 24,
} as const;

/** Erros com código estável, mapeados para mensagens amigáveis no client. Nunca revelam se o e-mail existe. */
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TWO_FACTOR_REQUIRED: "TWO_FACTOR_REQUIRED",
  INVALID_TWO_FACTOR_CODE: "INVALID_TWO_FACTOR_CODE",
  RATE_LIMITED: "RATE_LIMITED",
  /** A nova senha é igual à que já estava em uso. */
  SAME_PASSWORD: "SAME_PASSWORD",
} as const;
