import type { ScreenerConfig } from "@/types/screener";

export const STOCK_SCREENER_CONFIG: ScreenerConfig = {
  title: "Screener de Ações",
  description: "Filtre e compare ações e BDRs da B3 por indicadores fundamentalistas.",
  csvName: "screener-acoes",
  columns: [
    { key: "score", label: "Nota", format: "score" },
    { key: "sector", label: "Setor", format: "text", minWidth: "min-w-36" },
    { key: "price", label: "Preço", format: "currency" },
    { key: "pl", label: "P/L", format: "number" },
    { key: "pvp", label: "P/VP", format: "number" },
    { key: "dy", label: "DY", format: "percent" },
    { key: "roe", label: "ROE", format: "percent" },
    { key: "roic", label: "ROIC", format: "percent" },
    { key: "netMargin", label: "Marg. Líq.", format: "percent" },
    { key: "ebitdaMargin", label: "Marg. EBITDA", format: "percent" },
    { key: "evEbit", label: "EV/EBIT", format: "number" },
    { key: "evEbitda", label: "EV/EBITDA", format: "number" },
    { key: "liquidity", label: "Liquidez", format: "compact" },
    { key: "tagAlong", label: "Tag Along", format: "percent" },
    { key: "freeFloat", label: "Free Float", format: "percent" },
    { key: "revenueGrowth", label: "Cresc. Receita", format: "percent" },
    { key: "earningsGrowth", label: "Cresc. Lucro", format: "percent" },
    { key: "netDebt", label: "Dív. Líquida", format: "compact" },
    { key: "netDebtEbitda", label: "Dív/EBITDA", format: "number" },
    { key: "equity", label: "Patrimônio", format: "compact" },
    { key: "marketCap", label: "Valor Mercado", format: "compact" },
  ],
  filters: [
    { key: "score", label: "Nota do ativo", kind: "range" },
    { key: "sector", label: "Setor", kind: "select" },
    { key: "subsector", label: "Subsetor", kind: "select" },
    { key: "pl", label: "P/L", kind: "range" },
    { key: "pvp", label: "P/VP", kind: "range" },
    { key: "dy", label: "Dividend Yield", kind: "range", unit: "%" },
    { key: "roe", label: "ROE", kind: "range", unit: "%" },
    { key: "roic", label: "ROIC", kind: "range", unit: "%" },
    { key: "netMargin", label: "Margem Líquida", kind: "range", unit: "%" },
    { key: "ebitdaMargin", label: "Margem EBITDA", kind: "range", unit: "%" },
    { key: "evEbit", label: "EV/EBIT", kind: "range" },
    { key: "evEbitda", label: "EV/EBITDA", kind: "range" },
    { key: "liquidity", label: "Liquidez diária (R$)", kind: "range" },
    { key: "tagAlong", label: "Tag Along", kind: "range", unit: "%" },
    { key: "freeFloat", label: "Free Float", kind: "range", unit: "%" },
    { key: "revenueGrowth", label: "Crescimento Receita", kind: "range", unit: "%" },
    { key: "earningsGrowth", label: "Crescimento Lucro", kind: "range", unit: "%" },
    { key: "netDebtEbitda", label: "Dívida/EBITDA", kind: "range" },
    { key: "equity", label: "Patrimônio (R$)", kind: "range" },
    { key: "marketCap", label: "Valor de Mercado (R$)", kind: "range" },
  ],
};
